name: freecad test
on: push
jobs:
  freecad_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install freecad
        run: |
          sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
          sudo apt-get update
          sudo apt-get install -y freecad-python3