name: test-action
on: push
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Create readme
        run: |
          python ./.github/workflows/test.py
      - name: Commit readme
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git diff --quiet && git diff --staged --quiet || git commit -am 'Auto updated readme table'
          git push